### ISSUE TITLE
Installing Voxel

### ISSUE THREAD

**Issue by nvladimus** [AllenNeuralDynamics/voxel#73]
Hi, everyone,
I am trying to install Voxel and try it out with simulated devices. Alas, got stuck at the installation step...

- OS: Windows
- package manager: conda, new clean evironment
- pip version: 24.2
- Python versions: 3.7.16 or 3.9.20 (see error logs below)

Many thanks!
Nikita

 ## Error log with Python 3.7.16
```
(allen_voxel) C:\Users\Nikita\Documents\GitHub\voxel>pip install -e .
Obtaining file:///C:/Users/Nikita/Documents/GitHub/voxel
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
Collecting pycobolt@ git+https://github.com/cobolt-lasers/pycobolt.git
  Cloning https://github.com/cobolt-lasers/pycobolt.git to c:\users\nikita\appdata\local\temp\pip-install-vc0sipiy\pycobolt_1c1d17321b474dabae24d0b84be7dcd2
  Running command git clone --filter=blob:none --quiet https://github.com/cobolt-lasers/pycobolt.git 'C:\Users\Nikita\AppData\Local\Temp\pip-install-vc0sipiy\pycobolt_1c1d17321b474dabae24d0b84be7dcd2'
  Resolved https://github.com/cobolt-lasers/pycobolt.git to commit e19bfafed77364a746545605629d6c2cdf661031
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
ERROR: Ignored the following versions that require a different python version: 1.10.0 Requires-Python <3.12,>=3.8; 1.10.0rc1 Requires-Python <3.12,>=3.8; 1.10.0rc2 Requires-Python <3.12,>=3.8; 1.10.1 Requires-Python <3.12,>=3.8; 1.11.0 Requires-Python <3.13,>=3.9; 1.11.0rc1 Requires-Python <3.13,>=3.9; 1.11.0rc2 Requires-Python <3.13,>=3.9; 1.11.1 Requires-Python <3.13,>=3.9; 1.11.2 Requires-Python <3.13,>=3.9; 1.11.3 Requires-Python <3.13,>=3.9; 1.11.4 Requires-Python >=3.9; 1.12.0 Requires-Python >=3.9; 1.12.0rc1 Requires-Python >=3.9; 1.12.0rc2 Requires-Python >=3.9; 1.13.0 Requires-Python >=3.9; 1.13.0rc1 Requires-Python >=3.9; 1.13.1 Requires-Python >=3.9; 1.14.0 Requires-Python >=3.10; 1.14.0rc1 Requires-Python >=3.10; 1.14.0rc2 Requires-Python >=3.10; 1.14.1 Requires-Python >=3.10; 1.8.0 Requires-Python >=3.8,<3.11; 1.8.0rc1 Requires-Python >=3.8,<3.11; 1.8.0rc2 Requires-Python >=3.8,<3.11; 1.8.0rc3 Requires-Python >=3.8,<3.11; 1.8.0rc4 Requires-Python >=3.8,<3.11; 1.8.1 Requires-Python >=3.8,<3.11; 1.9.0 Requires-Python >=3.8,<3.12; 1.9.0rc1 Requires-Python >=3.8,<3.12; 1.9.0rc2 Requires-Python >=3.8,<3.12; 1.9.0rc3 Requires-Python >=3.8,<3.12; 1.9.1 Requires-Python >=3.8,<3.12; 1.9.2 Requires-Python >=3.8; 1.9.3 Requires-Python >=3.8
ERROR: Could not find a version that satisfies the requirement scipy>=1.12.0 (from voxel) (from versions: 0.8.0, 0.9.0, 0.10.0, 0.10.1, 0.11.0, 0.12.0, 0.12.1, 0.13.0, 0.13.1, 0.13.2, 0.13.3, 0.14.0, 0.14.1, 0.15.0, 0.15.1, 0.16.0, 0.16.1, 0.17.0, 0.17.1, 0.18.0, 0.18.1, 0.19.0, 0.19.1, 1.0.0, 1.0.1, 1.1.0, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.4.0, 1.4.1, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.6.0, 1.6.1, 1.6.2, 1.6.3, 1.7.0, 1.7.1, 1.7.2, 1.7.3)
ERROR: No matching distribution found for scipy>=1.12.0
```

### Error log with Python 3.9.20
```
Collecting pytest>=8.2.1 (from voxel==0.0.0)
  Downloading pytest-8.3.2-py3-none-any.whl.metadata (7.5 kB)
  Downloading pytest-8.3.1-py3-none-any.whl.metadata (7.5 kB)
  Downloading pytest-8.3.0-py3-none-any.whl.metadata (7.5 kB)
  Downloading pytest-8.2.2-py3-none-any.whl.metadata (7.6 kB)
  Downloading pytest-8.2.1-py3-none-any.whl.metadata (7.6 kB)
Collecting gputools>=0.2.14 (from voxel==0.0.0)
  Downloading gputools-0.2.14-py3-none-any.whl.metadata (1.2 kB)
Collecting numpy<1.24.0 (from gputools>=0.2.14->voxel==0.0.0)
  Downloading numpy-1.23.5-cp39-cp39-win_amd64.whl.metadata (2.3 kB)
Collecting pydantic>=2.7.3 (from voxel==0.0.0)
  Downloading pydantic-2.9.1-py3-none-any.whl.metadata (146 kB)
Collecting pydantic-core==2.23.3 (from pydantic>=2.7.3->voxel==0.0.0)
  Downloading pydantic_core-2.23.3-cp39-none-win_amd64.whl.metadata (6.7 kB)
Collecting pydantic>=2.7.3 (from voxel==0.0.0)
  Downloading pydantic-2.9.0-py3-none-any.whl.metadata (146 kB)
Collecting pydantic-core==2.23.2 (from pydantic>=2.7.3->voxel==0.0.0)
  Downloading pydantic_core-2.23.2-cp39-none-win_amd64.whl.metadata (6.7 kB)
Collecting tzdata (from pydantic>=2.7.3->voxel==0.0.0)
  Downloading tzdata-2024.2-py2.py3-none-any.whl.metadata (1.4 kB)
ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\Nikita\anaconda3\envs\allen_voxel\lib\site-packages\pip\_internal\cli\base_command.py", line 105, in _run_wrapper
    status = _inner_run()
  File "C:\Users\Nikita\anaconda3\envs\allen_voxel\lib\site-packages\pip\_internal\cli\base_command.py", line 96, in _inner_run
    return self.run(options, args)
  File "C:\Users\Nikita\anaconda3\envs\allen_voxel\lib\site-packages\pip\_internal\cli\req_command.py", line 67, in wrapper
    return func(self, options, args)
  File "C:\Users\Nikita\anaconda3\envs\allen_voxel\lib\site-packages\pip\_internal\commands\install.py", line 379, in run
    requirement_set = resolver.resolve(
  File "C:\Users\Nikita\anaconda3\envs\allen_voxel\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 95, in resolve
    result = self._result = resolver.resolve(
  File "C:\Users\Nikita\anaconda3\envs\allen_voxel\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "C:\Users\Nikita\anaconda3\envs\allen_voxel\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 457, in resolve
    raise ResolutionTooDeep(max_rounds)
pip._vendor.resolvelib.resolvers.ResolutionTooDeep: 200000
```

**Comment by nvladimus** [comment]
Hi, everyone,
Thanks for the updates for pre-release. I was able to install with Py 3.11 👍
